### ISSUE TITLE
Toolboxes crash in Debug when creating the mesh

### ISSUE THREAD

**Issue by romainhild** [feelpp/feelpp#1157]
@vincentchabannes the function createmesh has a segfault in debug mode.
I tried for example the HL-31_H1 test case in thermoelectric.

This does not happen in Release mode.
Here is the backtrace:
```
#0  Feel::GeoEntity<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double>::id (this=0x7fff00007fff) at /home/u2/hild/Devel/hifimagnet/feel/feelmesh/geoentity.hpp:210
#1  0x00007fffc1a188c5 in Feel::GeoElement3D<(unsigned short)3, Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double>::id (this=0x7fff00007fff)
    at /home/u2/hild/Devel/hifimagnet/feel/feelmesh/geoelement.hpp:1494
#2  0x00007fffc1a18968 in Feel::Elements<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double>::addElement(Feel::GeoElement3D<(unsigned short)3, Feel::Simplex<(unsigned short)3,
(unsigned short)1, (unsigned short)3>, double>&&) (this=0xb7b260,
    f=<unknown type in /ssd/hild/builds/hifi_debug/toolboxes/feel/feelmodels/modelmesh/libfeelpp_modelmesh.so, CU 0x0, DIE 0x291c4a>) at /home/u2/hild/Devel/hifimagnet/feel/feelmesh/elements.hpp:716
#3  0x00007fffc1a180eb in Feel::ImporterGmsh<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >::addVolume (this=0x7fffffff4a80, mesh=0xb7b100, __e=...,
    __idGmshToFeel=@0x3233824: 0)
    at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/importergmsh.hpp:1831
#4  0x00007fffc1a0603d in Feel::ImporterGmsh<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >::addVolume (this=0x7fffffff4a80, mesh=0xb7b100, __e=...,
    __idGmshToFeel=@0x3233824: 0)
    at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/importergmsh.hpp:1755
#5  0x00007fffc1a0486e in Feel::ImporterGmsh<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >::readFromFile (this=0x7fffffff4a80, mesh=0xb7b100)
    at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/importergmsh.hpp:1319
#6  0x00007fffc19fc0cd in Feel::ImporterGmsh<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >::visit (this=0x7fffffff4a80, mesh=0xb7b100)
    at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/importergmsh.hpp:636
#7  0x00007fffbf484e1e in Feel::VisitableBase<void, Feel::VisitableCatchAllDefault>::acceptImpl<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> > (
    visited=0xb7b100, guest=0x7fffffff4a80)
    at /home/u2/hild/Devel/hifimagnet/feel/feelcore/visitor.hpp:302
#8  0x00007fffbf484d7d in Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0>::accept (this=0xb7b100, guest=warning: RTTI symbol not found for class 'Feel::Import
erGmsh<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >'
...)
    at /home/u2/hild/Devel/hifimagnet/feel/feeldiscr/mesh.hpp:1323
#9  0x00007fffc1a299db in Feel::boost_param_default_74loadGMSHMesh<boost::shared_ptr<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >, boost::param[713/3003]
:arg_list<boost::parameter::aux::tagged_argument<Feel::tag::verbose, int> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partition_file, int const> const, boost::
parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partitioner, int const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partitions, unsi
gned short const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_partitions_filename, std::__cxx11::basic_string<char, std::char_traits<char>, std::alloca
tor<char> > > const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_partitions, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argume
nt<Feel::tag::respect_partition, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::worldcomm, Feel::WorldComm> const, boost::parameter::aux::arg_list<boost::pa
rameter::aux::tagged_argument<Feel::tag::physical_are_elementary_regions, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::update, int const> const, boost::pa
rameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::scale, double const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::refine, int const> co
nst, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::straighten, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Fee---Type <return> t
---Type <return> to continue, or q <return> to quit---
l::tag::filename, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::mesh, Feel
::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0>* const> const, boost::parameter::aux::empty_arg_list> > > > > > > > > > > > > > >, Feel::Mesh<Feel::Simplex<(unsig
ned short)3, (unsigned short)1, (unsigned short)3>, double, 0>* const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_tra
its<char>, std::allocator<char> >, double const, bool, int const, int const, bool, Feel::WorldComm, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned sh
ort const, int const, int const, int> (mesh=@0x7fffffffb848: 0xb7b100, filename="/ssd/hild/builds/hifi_debug/toolboxes/thermoelectric/ElectroMagnets/HL-31_H1/HL-31_H1-coarse.msh", prefix="",
    scale=@0x7fffffffacc0: 1, straighten=@0x7fffffffaa8f: true, refine=@0x7fffffffa814: 0, update=@0x7fffffffb7d4: 3, physical_are_elementary_regions=@0x7fffffffa40f: false, worldcomm=...,
    respect_partition=@0x7fffffff5de7: false, rebuild_partitions=@0x7fffffff5c7f: true, rebuild_partitions_filename="/data/scratch/hild/feel/toolboxes/thermoelectric/HL-31_H1/np_1/thermo-electric.msh",
    partitions=@0x7fffffffb7f6: 1, partitioner=@0x7fffffff8f34: 1, partition_file=@0x7fffffff87b4: 0, verbose=@0x7fffffff5384: 5) at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/loadgmshmesh.hpp:143
#10 0x00007fffc1a28a96 in Feel::boost_param_default_74loadGMSHMesh<boost::shared_ptr<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >, boost::parameter::aux:
:arg_list<boost::parameter::aux::tagged_argument<Feel::tag::verbose, int> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partition_file, int const> const, boost::
parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partitioner, int const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partitions, unsi
gned short const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_partitions_filename, std::__cxx11::basic_string<char, std::char_traits<char>, std::alloca
tor<char> > > const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_partitions, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argume
nt<Feel::tag::respect_partition, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::worldcomm, Feel::WorldComm> const, boost::parameter::aux::arg_list<boost::pa
rameter::aux::tagged_argument<Feel::tag::physical_are_elementary_regions, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::update, int const> const, boost::pa
rameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::scale, double const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::refine, int const> co
nst, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::straighten, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::filename,
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::mesh, Feel::Mesh<Feel::Simpl
ex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0>* const> const, boost::parameter::aux::empty_arg_list> > > > > > > > > > > > > > >, Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsi
gned short)1, (unsigned short)3>, double, 0>* const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::al
locator<char> >, double const, bool, int const, int const, bool, Feel::WorldComm, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short const, int con
st, int const> (args=..., mesh=@0x7fffffffb848: 0xb7b100, filename="/ssd/hild/builds/hifi_debug/toolboxes/thermoelectric/ElectroMagnets/HL-31_H1/HL-31_H1-coarse.msh", prefix="",
    scale=@0x7fffffffacc0: 1, straighten=@0x7fffffffaa8f: true, refine=@0x7fffffffa814: 0, update=@0x7fffffffb7d4: 3, physical_are_elementary_regions=@0x7fffffffa40f: false, worldcomm=...,
    respect_partition=@0x7fffffff5de7: false, rebuild_partitions=@0x7fffffff5c7f: true, rebuild_partitions_filename="/data/scratch/hild/feel/toolboxes/thermoelectric/HL-31_H1/np_1/thermo-electric.msh",
    rtitions=@0x7fffffffb7f6: 1, partitioner=@0x7fffffff8f34: 1, partition_file=@0x7fffffff87b4: 0) at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/loadgmshmesh.hpp:47
...
#27 0x00007fffc1ad8dbf in Feel::boost_param_default_89loadMesh<boost::shared_ptr<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >, boost::parameter::aux::arg
---Type <return> to continue, or q <return> to quit---
_list<boost::parameter::aux::tagged_argument<Feel::tag::update, int const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::savehdf5, int const> const, boost::param
eter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partitions, unsigned short const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_par
titions_filename, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_partiti
ons, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::prefix, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const, bo
ost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::worldcomm, Feel::WorldComm const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::f
ilename, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::mesh, Feel::Mesh<Fe
el::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0>* const> const, boost::parameter::aux::empty_arg_list> > > > > > > > >, Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigne
d short)1, (unsigned short)3>, double, 0>* const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<c
har> > const, boost::shared_ptr<Feel::Gmsh> const, double const, double const, bool, int const, int const, bool, Feel::WorldComm, bool const, bool, bool, std::__cxx11::basic_string<char, std::char_traits<
char>, std::allocator<char> >, unsigned short const, int const, int const, int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> (
    mesh=@0x7fffffffb848: 0xb7b100, prefix="thermo-electric", filename="/ssd/hild/builds/hifi_debug/toolboxes/thermoelectric/ElectroMagnets/HL-31_H1/HL-31_H1-coarse.msh", desc=...,
    h=@0x7fffffffaeb0: 0.10000000000000001, scale=@0x7fffffffacc0: 1, straighten=@0x7fffffffaa8f: true, refine=@0x7fffffffa814: 0, update=@0x7fffffffb7d4: 3,
    physical_are_elementary_regions=@0x7fffffffa40f: false, worldcomm=..., force_rebuild=@0x7fffffff9d6f: true, respect_partition=@0x7fffffff99b7: false, rebuild_partitions=@0x7fffffff97d7: true,
    rebuild_partitions_filename="/data/scratch/hild/feel/toolboxes/thermoelectric/HL-31_H1/np_1/thermo-electric.msh", partitions=@0x7fffffffb7f6: 1, partitioner=@0x7fffffff8f34: 1,
    savehdf5=@0x7fffffffb7e4: 0, partition_file=@0x7fffffff87b4: 0, depends="", verbose=@0x7fffffff7c74: 5) at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/loadmesh.hpp:190
#28 0x00007fffc1ad6ed1 in Feel::boost_param_default_89loadMesh<boost::shared_ptr<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> >, boost::parameter::aux::arg
_list<boost::parameter::aux::tagged_argument<Feel::tag::update, int const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::savehdf5, int const> const, boost::param
eter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::partitions, unsigned short const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_par
titions_filename, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::rebuild_partiti
ons, bool> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::prefix, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const, bo
ost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::worldcomm, Feel::WorldComm const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::f
ilename, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<Feel::tag::mesh, Feel::Mesh<Fe
el::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0>* const> const, boost::parameter::aux::empty_arg_list> > > > > > > > >, Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigne
d short)1, (unsigned short)3>, double, 0>* const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<c
har> > const, boost::shared_ptr<Feel::Gmsh> const, double const, double const, bool, int const, int const, bool, Feel::WorldComm, bool const, bool, bool, std::__cxx11::basic_string<char, std::char_traits<
char>, std::allocator<char> >, unsigned short const, int const, int const, int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> (args=...,
    mesh=@0x7fffffffb848: 0xb7b100, prefix="thermo-electric", filename="/ssd/hild/builds/hifi_debug/toolboxes/thermoelectric/ElectroMagnets/HL-31_H1/HL-31_H1-coarse.msh", desc=...,
    h=@0x7fffffffaeb0: 0.10000000000000001, scale=@0x7fffffffacc0: 1, straighten=@0x7fffffffaa8f: true, refine=@0x7fffffffa814: 0, update=@0x7fffffffb7d4: 3,
    physical_are_elementary_regions=@0x7fffffffa40f: false, worldcomm=..., force_rebuild=@0x7fffffff9d6f: true, respect_partition=@0x7fffffff99b7: false, rebuild_partitions=@0x7fffffff97d7: true,
    rebuild_partitions_filename="/data/scratch/hild/feel/toolboxes/thermoelectric/HL-31_H1/np_1/thermo-electric.msh", partitions=@0x7fffffffb7f6: 1, partitioner=@0x7fffffff8f34: 1,
    savehdf5=@0x7fffffffb7e4: 0, partition_file=@0x7fffffff87b4: 0, depends="") at /home/u2/hild/Devel/hifimagnet/feel/feelfilters/loadmesh.hpp:56
...
#62 0x00007fffc18fac79 in Feel::FeelModels::createMeshModel<Feel::Mesh<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, double, 0> > (model=warning: RTTI symbol not found for class
'Feel::FeelModels::ThermoElectric<Feel::FeelModels::Heat<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, Feel::Lagrange<(unsigned short)1, Feel::Scalar, Feel::Continuous, Feel::Poi
ntSetFekete, (unsigned short)0> >, Feel::FeelModels::Electric<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, Feel::Lagrange<(unsigned short)1, Feel::Scalar, Feel::Continuous, Feel
::PointSetFekete, (unsigned short)0> > >'
..., mesh=...,
    modelMeshRestartFile="thermo-electric.ThermoElectricMesh.path") at /home/u2/hild/Devel/hifimagnet/toolboxes/feel/feelmodels/modelmesh/createmesh.cpp:110
#63 0x00007fffe1b03951 in Feel::FeelModels::ThermoElectric<Feel::FeelModels::Heat<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, Feel::Lagrange<(unsigned short)1, Feel::Scalar, Fe
el::Continuous, Feel::PointSetFekete, (unsigned short)0> >, Feel::FeelModels::Electric<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, Feel::Lagrange<(unsigned short)1, Feel::Scala
r, Feel::Continuous, Feel::PointSetFekete, (unsigned short)0> > >::createMesh (this=0xb4f6f0) at /home/u2/hild/Devel/hifimagnet/toolboxes/feel/feelmodels/thermoelectric/thermoelectric.cpp:99
#64 0x00007fffe1b02ba3 in Feel::FeelModels::ThermoElectric<Feel::FeelModels::Heat<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, Feel::Lagrange<(unsigned short)1, Feel::Scalar, Fe
el::Continuous, Feel::PointSetFekete, (unsigned short)0> >, Feel::FeelModels::Electric<Feel::Simplex<(unsigned short)3, (unsigned short)1, (unsigned short)3>, Feel::Lagrange<(unsigned short)1, Feel::Scala
r, Feel::Continuous, Feel::PointSetFekete, (unsigned short)0> > >::ThermoElectric (this=0xb4f6f0, prefix="thermo-electric", buildMesh=true, worldComm=..., subPrefix="", modelRep=...)
    at /home/u2/hild/Devel/hifimagnet/toolboxes/feel/feelmodels/thermoelectric/thermoelectric.cpp:72
#65 0x0000000000422782 in runApplicationThermoElectric<1> () at /home/u2/hild/Devel/hifimagnet/toolboxes/thermoelectric/main_thermoelectric.cpp:16
#66 0x0000000000418bd6 in main (argc=3, argv=0x7fffffffccd8) at /home/u2/hild/Devel/hifimagnet/toolboxes/thermoelectric/main_thermoelectric.cpp:60
```

**Comment by prudhomm** [comment]
@vincentchabannes any idea ? should I move this to v107 ?

**Comment by vincentchabannes** [comment]
this was fixed long time ago
