### ISSUE TITLE
Deadlock in simulation using the fluid toolbox

### ISSUE THREAD

**Issue by lberti** [feelpp/feelpp#1753]
I ran the fluid toolbox (c++ and Python) on the Naca0012 example available here 
https://github.com/feelpp/feelpp/tree/rb_testcases/toolboxes/fluid/cases/rigid_body_paper_tests/naca0012_profile 
and the simulation blocks after 210 iterations. The following backtrace was obtained by launching the c++ toolbox in sequential in gdb
```
Thread 1 "feelpp_toolbox_" received signal SIGINT, Interrupt.
futex_abstimed_wait_cancelable (private=128, abstime=0x0, clockid=0, expected=0, futex_word=0x7fff45759000)
    at ../sysdeps/nptl/futex-internal.h:320
320     ../sysdeps/nptl/futex-internal.h: No such file or directory.
(gdb) bt
#0  futex_abstimed_wait_cancelable (private=128, abstime=0x0, clockid=0, expected=0, futex_word=0x7fff45759000)    at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x7fff45759000, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007fff5590a4e8 in __new_sem_wait_slow (sem=0x7fff45759000, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00007fff4401d598 in mca_sharedfp_sm_file_open () from /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_sharedfp_sm.so
#4  0x00007fff44229034 in mca_common_ompio_file_open () from /usr/lib/x86_64-linux-gnu/libmca_common_ompio.so.41
#5  0x00007fff444c50b3 in mca_io_ompio_file_open () from /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_io_ompio.so
#6  0x00007fff540d84ed in mca_io_base_file_select () from /usr/lib/x86_64-linux-gnu/libmpi.so.40
#7  0x00007fff5406168b in ompi_file_open () from /usr/lib/x86_64-linux-gnu/libmpi.so.40
#8  0x00007fff5408ddb9 in PMPI_File_open () from /usr/lib/x86_64-linux-gnu/libmpi.so.40
#9  0x00007fff557a1e79 in ?? () from /usr/lib/x86_64-linux-gnu/libhdf5_openmpi.so.103
#10 0x00007fff555d7efb in H5FD_open () from /usr/lib/x86_64-linux-gnu/libhdf5_openmpi.so.103
#11 0x00007fff555c750c in H5F_open () from /usr/lib/x86_64-linux-gnu/libhdf5_openmpi.so.103
#12 0x00007fff555c815a in H5F__create () from /usr/lib/x86_64-linux-gnu/libhdf5_openmpi.so.103
#13 0x00007fff555b9ba7 in H5Fcreate () from /usr/lib/x86_64-linux-gnu/libhdf5_openmpi.so.103
#14 0x00007fff56846bac in Feel::HDF5::openFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::mpi::communicator const&, bool const&, bool const&) () from /usr/lib/x86_64-linux-gnu/libfeelpp.so.1
#15 0x00007fff569e8428 in Feel::VectorUblas<double, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >::saveHDF5(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) const () from /usr/lib/x86_64-linux-gnu/libfeelpp.so.1
#16 0x00007fff6e8127dd in Feel::Bdf<Feel::FunctionSpace<Feel::Mesh<Feel::Simplex<(unsigned short)2, (unsigned short)1, (unsigned short)2>, double, 0, unsigned int>, Feel::bases<Feel::Lagrange<(unsigned short)1, Feel::Vectorial, Feel::Continuous, Feel::PointSetFekete, (unsigned short)0> >, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_> >::saveCurrent() ()   from /usr/lib/x86_64-linux-gnu/libfeelpp_modelmeshale.so.1.0
#17 0x00007fff6e51e9ce in Feel::FeelModels::MeshALE<Feel::Simplex<(unsigned short)2, (unsigned short)1, (unsigned short)2> >::updateTimeStep() () from /usr/lib/x86_64-linux-gnu/libfeelpp_modelmeshale.so.1.0
#18 0x00007ffff32dbdc9 in Feel::FeelModels::FluidMechanics<Feel::Simplex<(unsigned short)2, (unsigned short)1, (unsigned short)2>, Feel::Lagrange<(unsigned short)2, Feel::Vectorial, Feel::Continuous, Feel::PointSetFekete, (unsigned short)0>, Feel::Lagrange<(unsigned short)1, Feel::Scalar, Feel::Continuous, Feel::PointSetFekete, (unsigned short)0> >::updateTimeStep() ()
   from /usr/lib/x86_64-linux-gnu/libfeelpp_toolbox_fluid_lib_2dP2P1G1.so.1.0
#19 0x0000000000418509 in int Feel::runApplicationFluid<2, (unsigned short)2, (unsigned short)1, (unsigned short)1>() ()
#20 0x000000000040fb08 in main ()
```

**Comment by lberti** [comment]
The error was linked to hardware problems in the cluster where the simulations were launched.
